### ISSUE TITLE
parse sdk denpendency throw exception

### ISSUE THREAD

**Issue by josercc** [matthewnitschke/pubspec_lock_parse#8]
```yaml
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
```

```dart
throw FormatException('Unknown package description type');
```
